Made some updates based on the new design of login page including
micromentor-team/mm-flutter-app pull request #106
Opened 2023-08-22 12:05 UTC by ashlilili

1. extracted social sign in buttons (will be reused for sign up page)
2. adjusted some details such as padding and text
<img width="473" alt="Screenshot 2023-08-22 at 8 04 51 PM" src="https://github.com/micromentor-team/mm-flutter-app/assets/100324646/e1a38aed-a85e-414d-b548-1238629fb4ad">

2023-08-22 16:51 UTC, LucasMagnum approved these changes

2023-08-22 17:23 UTC, m-rosario requested changes
Looks very slick, but did you use a Web browser to test this? When I run it in my Android emulator the vertical spacing seems excessive to the point I have to scroll to see all the buttons. 

<img width="316" alt="Screenshot 2023-08-22 at 10 03 28 AM" src="https://github.com/micromentor-team/mm-flutter-app/assets/25093428/8e3cd8a5-01e6-4ce3-9bc5-e65ac53a40b8">


I believe this is yet another instance of the difference in rendering between web and mobile versions. I used the Flutter Inspector to show the difference in padding side-by-side (Web left vs Android right):


<img width="792" alt="Screenshot 2023-08-22 at 10 14 43 AM" src="https://github.com/micromentor-team/mm-flutter-app/assets/25093428/d5a9dc95-f6ea-47bd-beff-1b593a30a054">


Note all the extra padding in the Android version. I don't think we can get away from having to create multiple versions of the UI in order to accommodate different platforms and screen sizes, but for now we can at least focus on making it look good on phones.

2023-08-23 08:48 UTC, ashlilili commented
![image](https://github.com/micromentor-team/mm-flutter-app/assets/100324646/f8287519-26cc-45a5-a43c-11b9873d652b)

Thanks Miguel for testing it on Android. I removed the extra paddings, it now looks like above

2023-08-23 15:44 UTC, m-rosario approved these changes
Thanks!!

2023-08-23 16:58 UTC, merged