Edit profile about my business
micromentor-team/mm-flutter-app pull request #180
Opened 2023-10-19 02:17 UTC by ashlilili

Adding "about my business" section for entrepreneur users

https://github.com/micromentor-team/mm-flutter-app/assets/100324646/17bd4d87-410c-4f79-9c8e-32cefb884886

2023-10-19 17:15 UTC, m-rosario requested changes
Looks good so far, but it is missing the **Business name** section.

Also make sure that you can run it with the real backend, on a profile that has only the minimum required fields. I get errors when trying it on the real backend. I would also suggest creating a test branch that merges with https://github.com/micromentor-team/mm-flutter-app/pull/179 to make sure that you can access the profile sections now that the signup flow is shorter and missing a lot of the fields we had before.

2023-10-20 16:45 UTC, ashlilili commented
> Looks good so far, but it is missing the **Business name** section.
> 
> Also make sure that you can run it with the real backend, on a profile that has only the minimum required fields. I get errors when trying it on the real backend. I would also suggest creating a test branch that merges with #179 to make sure that you can access the profile sections now that the signup flow is shorter and missing a lot of the fields we had before.

I tried to connect to the real backend, but it threw an error on profile page, before I could go to edit profile

```
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following TypeErrorImpl was thrown building Selector<InboxModel,
Tuple2<List<Query$36MyReceivedChannelInvitations$36myChannelInvitations>?,
List<Query$36MySentChannelInvitations$36myChannelInvitations>?>>(dirty, dependencies:
[_InheritedProviderScope<InboxModel?>], state:
_Selector0State<Tuple2<List<Query$36MyReceivedChannelInvitations$36myChannelInvitations>?,
List<Query$36MySentChannelInvitations$36myChannelInvitations>?>>#2c8a6(value: [[], []])):
Unexpected null value.
The relevant error-causing widget was:
  Selector<InboxModel, Tuple2<List<Query$36MyReceivedChannelInvitations$36myChannelInvitations>?,
  List<Query$36MySentChannelInvitations$36myChannelInvitations>?>>
```

2023-10-21 14:20 UTC, m-rosario commented
> > Looks good so far, but it is missing the **Business name** section.
> > Also make sure that you can run it with the real backend, on a profile that has only the minimum required fields. I get errors when trying it on the real backend. I would also suggest creating a test branch that merges with #179 to make sure that you can access the profile sections now that the signup flow is shorter and missing a lot of the fields we had before.
> 
> I tried to connect to the real backend, but it threw an error on profile page, before I could go to edit profile
> 
> ```
> ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
> The following TypeErrorImpl was thrown building Selector<InboxModel,
> Tuple2<List<Query$36MyReceivedChannelInvitations$36myChannelInvitations>?,
> List<Query$36MySentChannelInvitations$36myChannelInvitations>?>>(dirty, dependencies:
> [_InheritedProviderScope<InboxModel?>], state:
> _Selector0State<Tuple2<List<Query$36MyReceivedChannelInvitations$36myChannelInvitations>?,
> List<Query$36MySentChannelInvitations$36myChannelInvitations>?>>#2c8a6(value: [[], []])):
> Unexpected null value.
> The relevant error-causing widget was:
>   Selector<InboxModel, Tuple2<List<Query$36MyReceivedChannelInvitations$36myChannelInvitations>?,
>   List<Query$36MySentChannelInvitations$36myChannelInvitations>?>>
> ```

I am not getting this error so I do not know what this is about. I will merge this PR as it is and create another one for fixes.

2023-10-21 14:20 UTC, m-rosario approved these changes

2023-10-21 14:20 UTC, merged